### ISSUE TITLE
✅ weitere Anforderungen (Brainstorming)

### ISSUE THREAD

**Issue by OLILHR** [OLILHR/ebd.hochfrequenz.de#88]
> [!NOTE]
> gemäß https://github.com/Hochfrequenz/ebd_parser-frontend/issues?q=is%3Aissue+is%3Aclosed
> **übergeordnete Sammlung offener To-Do's, die anschließend in einzelne Github Issues verpackt werden.**
> 
> für fachliche Anforderungen, siehe https://github.com/Hochfrequenz/entscheidungsbaumdiagramm/issues/58

- [x] Einloggen/Ausloggen -> [Anmelden/Abmelden](https://github.com/Hochfrequenz/ebd_parser-frontend/issues/54) #106 Edit: lassen wir so; ist bei Bedingungsbaum genau so
- [x] Landingpage texts/banners #71 
- [x] Custom 404 fallback #102
- [x] ahbesser deeplinks -> ebds https://github.com/Hochfrequenz/ahbesser/issues/368
- ~~perhaps pruefiID deeplinks to AHB-Tabellen // requires pruefID <-> EBD mapping~~
- ~~if someone is bored to death: a responsive design for mobile (?)~~
- [x] quick return/nav button in the middle of 404 pages (`/ebd/` landingpage redirection)

**Comment by OLILHR** [comment]
~~brauchen wir eine "Suche" auf der Seite? brauchen wir Links mit query parameter um ein EBD + gehighlighteten Suchbegriff an andere weiterzuleiten?~~

**Comment by hf-nsoeker** [comment]
Ein Lupen Tool fänd ich gut. Derzeit kann man nicht ans Diagramm ranszoomen.

**Comment by OLILHR** [comment]
> Ein Lupen Tool fänd ich gut. Derzeit kann man nicht ans Diagramm ranszoomen.

gabs schon mal als Issue aber die Implementierung war nicht so easy, bzw. war das mit viel Customizing und Gepfusche verbunden. Habe ich aber auf dem Schirm!
